syntax on
colorscheme darkblue
set statusline=%-3.60([%F]%)[%{strlen(&fenc)?&fenc:'none'}]%(%r%m%h%w%y%)%=[0x%02B(%03b)][L%l/%L][%c/%v][%P]
set laststatus=2
set wildmenu
set showmatch
autocmd BufNewFile,BufRead *.psp setlocal filetype=python
autocmd BufNewFile,BufRead *.ino setlocal filetype=python
au BufEnter *.py set sw=4 sts=4 et ai
au BufEnter *.zcml set sw=4 sts=4 et ai filetype=xml
au BufEnter *.xml set sw=4 sts=4 et ai
au BufEnter *.c set sw=4 sts=4 et ai foldmethod=indent
au BufEnter *.conf set sw=4 sts=4 filetype=conf
au BufEnter *.html set sw=4 sts=4 et ai filetype=htmldjango
au BufEnter *.pt set sw=2 sts=2 et ai filetype=html
au BufEnter *.js set sw=4 sts=4 et ai cindent formatoptions=acroq textwidth=70
au BufEnter *.pas set sw=4 sts=4 et ai
au BufEnter *.rb set sw=4 sts=4 et ai
au BufEnter *.c set sw=4 sts=4 et ai
au BufEnter *.erl set sw=4 sts=4 et ai
au BufEnter *.java set sw=4 sts=4 et ai cindent formatoptions=acroq textwidth=70
